[project]
name = "veritas"
version = "1.0.0"
entry-point = "main.jac"

[dependencies.npm]
cytoscape = "^3.26.0"

[serve]
base_route_app = ""

[plugins.client]

[plugins.byllm.model]
default_model = "openai/gpt-4o-mini"
api_key = "YOUR_OPENROUTER_API_KEY"
base_url = "https://openrouter.ai/api/v1"

